[package]
name = "encrypted-sql-ops-ecall-types"
version = "0.1.0"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
serde-std = { package = "serde", version = "1", default-features = false, optional = true }
serde-sgx = { package = "serde", git = "https://github.com/mesalock-linux/serde-sgx.git", default-features = false, optional = true, features = ["derive"] }

[features]
default = ["std"]
std = [
    "serde-std",
]
sgx = [
    "serde-sgx",
]
