[package]
name = "erc20-state-transition"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
frame-runtime = { path = "../../../frame/runtime", default-features = false }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[features]
default = ["std"]
std = [
    "frame-runtime/std",
]
sgx = [
    "frame-runtime/sgx",
    "sgx_tstd",
]
