[package]
name = "dx-server"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
dx-api = { path = "../api" }
dx-app = { path = "../app" }
anonify-common = { path = "../../../core/common" }
anonify-runtime = { path = "../../../core/runtime" }
anonify-host = { path = "../../../core/host" }
anonify-bc-connector = { path = "../../../core/bc-connector" }
anonify-wallet = { path = "../../../wallet" }
sgx_types = "1.1.1"
actix-web = "1.0"
failure = "0.1"
log = "0.4"
env_logger = "0.7"
ed25519-dalek = "1.0.0-pre.2"
#hex = "0.4"
anyhow = "1.0"
reqwest = "0.9"
serde_json = "1.0.55"
lazy_static = "1.4.0"
rand = "0.7"
dirs = "2.0"
