[package]
name = "anonify-enclave"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[lib]
name = "anonifyenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
anonify-types = { path = "../types", default-features = false, features = ["sgx"] }
elastic-array = { version = "0.10", git = "https://github.com/mesalock-linux/elastic-array-sgx.git" }
ed25519-dalek = { version = "0.9.1", default-features = false, features = ["u64_backend"] }
byteorder = { version = "1", default-features = false }
sha2 = { version = "0.8", default-features = false }
ring = { rev = "sgx_1.0.9", git = "https://github.com/mesalock-linux/ring-sgx" }

sgx_tse = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tstd = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git", features = ["untrusted_fs","net","backtrace"] }
sgx_rand = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_types = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_trts = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tcrypto  = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tseal  = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git" }
