[package]
name = "anonify-enclave"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[lib]
name = "anonifyenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
kvdb = { git = "https://github.com/mesalock-linux/parity-common-sgx" }
kvdb-memorydb = { git = "https://github.com/mesalock-linux/parity-common-sgx" }
anonify-common = { path = "../common", default-features = false, features = ["sgx"] }

sgx_tse = { rev = "v1.0.9", git = "https://github.com/apache/mesatee-sgx" }
sgx_tstd = { rev = "v1.0.9", git = "https://github.com/apache/mesatee-sgx", features = ["untrusted_fs","net","backtrace"] }
sgx_rand = { rev = "v1.0.9", git = "https://github.com/apache/mesatee-sgx" }
sgx_types = { rev = "v1.0.9", git = "https://github.com/apache/mesatee-sgx" }
sgx_trts = { rev = "v1.0.9", git = "https://github.com/apache/mesatee-sgx" }
sgx_tcrypto  = { rev = "v1.0.9", git = "https://github.com/apache/mesatee-sgx" }
