[package]
name = "anonify-enclave"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
frame-types = { path = "../../frame/types" }
frame-enclave = { path = "../../frame/enclave" }
frame-runtime = { path = "../../frame/runtime", default-features = false, features = ["sgx"] }
frame-treekem = { path = "../../frame/treekem" }
frame-common = { path = "../../frame/common", default-features = false, features = ["sgx"] }
anonify-common = { path = "../common", default-features = false, features = ["sgx"] }

remote-attestation = { git = "https://github.com/LayerXcom/libsgx-rs" }
ed25519-dalek = { version = "1.0.0-pre.2", default-features = false, features = ["u64_backend"] }
libsecp256k1 = { version = "0.2", default-features = false }
hex = { version = "0.4", default-features = false }
codec = { package = "parity-scale-codec", version = "1.1", default-features = false }
anyhow = { rev = "sgx_1.1.2", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
thiserror = { git = "https://github.com/mesalock-linux/thiserror-sgx.git" }
base64 = { rev = "sgx_1.1.2", git = "https://github.com/mesalock-linux/rust-base64-sgx" }
log = { rev = "sgx_1.1.2", git = "https://github.com/mesalock-linux/log-sgx" }

sgx_tse = "1.1.1"
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net","backtrace"] }
sgx_types = "1.1.1"
