[package]
name = "anonify-enclave"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
frame-types = { path = "../../frame/types" }
frame-enclave = { path = "../../frame/enclave" }
frame-config = { path = "../../frame/config", default-features = false, features = ["sgx"] }
frame-ecies = { path = "../../frame/ecies", default-features = false, features = ["sgx"] }
frame-runtime = { path = "../../frame/runtime", default-features = false, features = ["sgx"] }
frame-treekem = { path = "../../frame/treekem", default-features = false, features = ["sgx"] }
frame-common = { path = "../../frame/common", default-features = false, features = ["sgx"] }
frame-mra-tls = { path = "../../frame/mra-tls" }
remote-attestation = { path = "../../frame/remote-attestation" }
anonify-ecall-types = { path = "../anonify-ecall-types", default-features = false, features = ["sgx"] }
test-utils = { path = "../../tests/utils" }
serde_json = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/serde-json-sgx" }
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git" } # Don't specify version due to serde_json dependency
bincode = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/bincode-sgx" }
libsecp256k1 = { version = "0.2", default-features = false }
anyhow = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
thiserror = { git = "https://github.com/mesalock-linux/thiserror-sgx.git" }
ed25519-dalek = { version = "1.0.0-pre.2", default-features = false, features = ["u64_backend"] }

sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net","backtrace"] }
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

[features]
default = ["backup-enable"]
backup-enable = []