[package]
name = "anonify-host"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
anonify-types = { path = "../types" }
sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_urts = { git = "https://github.com/baidu/rust-sgx-sdk.git" }
dirs = "2.0"
failure = "0.1.6"
serde = { version = "1.0", features=["serde_derive"] }
serde_json = "1.0"
reqwest = "0.9"
base64 = "0.11"
web3 = "0.8"
openssl = "0.10"
hex = "0.4"

[build-dependencies]
bindgen = "0.51"
dirs = "2.0"
