[package]
name = "anonify-host"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
anonify-types = { path = "../types" }
anonify-common = { path = "../common" }
sgx_types = "1.1.0"
sgx_urts = "1.1.0"
dirs = "2.0"
failure = "0.1.6"
serde_json = "1.0"
reqwest = "0.9"
web3 = "0.8"
ethabi = "8.0.0"
openssl = "0.10"
hex = "0.4"
rustc-hex = "2.0"
log = "0.4"
ed25519-dalek = "1.0.0-pre.2"
rand = "0.6"
rand_core = "0.3"
byteorder = "1"
parking_lot = "0.10"

[dev-dependencies]
rand_os = "0.1"
base64 = "0.11"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
bindgen = "0.51"
dirs = "2.0"
