kind: pipeline
type: docker
name: anonify-debug

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: osuketh/anonify:latest
  privileged: true
  volumes:
  - name: anonify
    path: /root/anonify
  - name: sgx
    path: /dev/sgx
  commands:
  - /bin/bash /root/anonify/scripts/test.sh

volumes:
- name: anonify
  host:
    path: ${PWD}/anonify
- name: sgx
  host:
    path: /dev/sgx