kind: pipeline
type: exec
name: anonify-debug

platform:
  os: linux
  arch: amd64

steps:
- name: hw-test
  commands:
    - docker run -v `pwd`:/root/anonify -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket --device /dev/sgx --net=test-network --name sgxci --rm osuketh/anonify:latest /bin/bash /root/anonify/scripts/test.sh
- name: Teardown
  commands:
    - docker stop sgxci || exit 0
  when:
    status:
      - failure
      - success
