kind: pipeline
type: docker
name: anonify-debug

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: osuketh/anonify:latest
  privileged: true
  volumes:
  - name: sgx
    path: /dev/sgx
  environment:
    PJ_ROOT_DIR: /drone/src/anonify
  commands:
  - /bin/bash ./scripts/test.sh

volumes:
- name: sgx
  host:
    path: /dev/sgx