kind: pipeline
type: exec
name: anonify-debug

platform:
  os: linux
  arch: amd64

steps:
- name: prepare
  image: osuketh/anonify:latest
  commands:
    - . /opt/sgxsdk/environment && . /root/.cargo/env
    - cp .env.template .env && cp example/server/.env.template example/server/.env
- name: Build contracts
  image: osuketh/anonify:latest
  commands:
    - solc -o build --bin --abi --optimize --overwrite contracts/AnonymousAsset.sol
- name: test
  image: osuketh/anonify:latest
  privileged: true
  volumes:
    - name: isgx
      path: /dev/isgx
  commands:
    - ./scripts/test.sh

volumes:
  - name: isgx
    host:
      path: /dev/isgx
  - name: sock
    host:
      path: /var/run/docker.sock