kind: pipeline
type: exec
name: anonify-debug

platform:
  os: linux
  arch: amd64

steps:
- name: hw-test
  commands:
    # - . /opt/sgxsdk/environment && . /root/.cargo/env
    # - cp .env.template .env && cp example/server/.env.template example/server/.env
    - docker run -v `pwd`:/root/anonify --device /dev/isgx --net=test-network --name sgxci --rm -it osuketh/anonify
    - solc -o build --bin --abi --optimize --overwrite contracts/AnonymousAsset.sol
    - ./scripts/test.sh
- name: Teardown
  commands:
    - docker stop sgxci || exit 0
  when:
    status:
      - failure
      - success
# - name: Build contracts
#   image: osuketh/anonify:latest
#   commands:
#     - solc -o build --bin --abi --optimize --overwrite contracts/AnonymousAsset.sol
# - name: test
#   image: osuketh/anonify:latest
#   privileged: true
#   volumes:
#     - name: isgx
#       path: /dev/isgx
#   commands:
#     - ./scripts/test.sh

# volumes:
#   - name: isgx
#     host:
#       path: /dev/isgx