kind: pipeline
type: exec
name: anonify-debug

platform:
  os: linux
  arch: amd64

steps:
- name: hw-test
  commands:
    # - . /opt/sgxsdk/environment && . /root/.cargo/env
    # - cp .env.template .env && cp example/server/.env.template example/server/.env
    - docker run -v `pwd`:/root/anonify --device /dev/isgx --net=test-network --name sgxci --rm osuketh/anonify:latest /bin/bash /root/anonify/scripts/test.sh
- name: Teardown
  commands:
    - docker stop sgxci
  when:
    status:
      - failure
      - success
