trigger:
- master

stages:
- stage: Test
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: CI
    pool:
      name: 'Anonify'
    container:
      image: osuketh/anonify:latest
      options: -v /root/anonify:/root/anonify -v /var/run/aesmd:/var/run/aesmd -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro --device /dev/sgx/enclave
    steps:
    - bash: ./scripts/test.sh

- stage: Docker_Build_and_Push
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: Docker
    pool:
      name: 'Anonify'
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: anonifydevdocker
        repository: anonifydev.azurecr.io/anonifydev
        tags: latest
        dockerfile: ./docker/server.Dockerfile
        buildContext: .