trigger:
- master

stages:
- stage: Test
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: CI
    pool:
      name: 'AnonifyDev'
    steps:
    - script: |
        cp .env.sample .env
        export SPID=$(SPID)
        export SUB_KEY=$(SUB_KEY)
        export ETH_HOST_PORT=$(ETH_HOST_PORT)
        export COMPOSE_PROJECT_NAME=$(COMPOSE_PROJECT_NAME)
        docker-compose up -d
        docker-compose exec -T sgx_machine bash -c "cd anonify && ./scripts/test.sh"
      displayName: 'Run tests'
    - script: docker-compose down
      condition: always()
      displayName: 'Shutdown'

- stage: Docker_Build_and_Push
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: Docker
    pool:
      name: 'AnonifyDev'
    steps:
    - task: Docker@2
      displayName: Build and Push anonify image
      inputs:
        command: buildAndPush
        containerRegistry: anonifydevdocker
        repository: anonifydev
        tags: latest
        dockerfile: ./docker/erc20.Dockerfile
        buildContext: .
    - task: Docker@2
      displayName: Build and Push key-vault image
      inputs:
        command: buildAndPush
        containerRegistry: anonifydevdocker
        repository: key-vault
        tags: latest
        dockerfile: ./docker/keyvault.Dockerfile
        buildContext: .
    - script: docker image prune -f
      displayName: Remove dangling images