trigger:
- master

stages:
- stage: Test
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: CI
    pool:
      name: 'AnonifyDev'
    steps:
    - script: |
        cp .env.sample .env
        export SPID=$(SPID)
        export SUB_KEY=$(SUB_KEY)
        docker-compose up -d
        docker-compose exec -T sgx_machine bash -c "cd anonify && ./scripts/test.sh"
      displayName: 'Run tests'
    - script: docker-compose down
      condition: always()
      displayName: 'Shutdown'
