[workspace]
members = [
    "core/enclave",
    "core/host",
    "core/runtime",
    "core/bc-connector",
    "core/common",
    "core/types",
    "core/treekem",
    "example/erc20/api",
    "example/erc20/cli",
    "example/erc20/enclave",
    "example/erc20/server",
    "example/erc20/state-transition",
    "example/invoice-dx/app",
    "example/invoice-dx/api",
    "wallet",
    "tests/integration",
    "tests/units/enclave",
    "tests/units/host",
]
exclude = [
    "example/invoice-dx/server",
]
