[workspace]
members = [
    "core/types",
    "core/runtime",
    "core/app-preluder",
    "core/bc-connector",
    "core/common",
    "example/erc20/cli",
    "example/erc20/api",
    "example/erc20/app",
    "wallet",
]
exclude = [
    "core/host",
    "core/enclave",
    "core/treekem",
    "example/erc20/server",
    "tests/utils",
]
