[workspace]
members = [
    "frame/enclave",
    "frame/host",
    "frame/common",
    "frame/types",
    "frame/treekem",
    "frame/runtime",
    "frame/remote-attestation",
    "frame/mra-tls",
    "frame/retrier",
    "frame/config",
    "modules/anonify-enclave",
    "modules/anonify-eth-driver",
    "modules/anonify-io-types",
    "modules/key-vault-enclave",
    "modules/key-vault-host",
    "example/erc20/api",
    "example/erc20/cli",
    "example/erc20/enclave",
    "example/erc20/server",
    "example/erc20/state-transition",
    "example/secret-backup/server",
    "example/secret-backup/api",
    "example/secret-backup/enclave",
    "config",
    "wallet",
    "tests/integration",
    "tests/units/enclave",
    "tests/units/host",
    "tests/utils",
]
