[workspace]
members = [
    "wallet",
    "core/types",
    "core/runtime",
    "example/cli",
    "example/anonymous-asset",
    "example/stf",
    "example/app",
]
exclude = [
    "core/enclave",
    "core/host",
    "core/common",
    "https-enclave",
    "example/server",
]
