[workspace]
members = [
    "wallet",
    "core/types",
    "core/runtime",
    "core/app-preluder",
    "example/cli",
    "example/api",
    "example/app",
]
exclude = [
    "core/enclave",
    "core/host",
    "core/common",
    "core/https-enclacve",
    "example/server",
]
