[workspace]
members = [
    "core/enclave",
    "core/host",
    "core/runtime",
    "core/bc-connector",
    "core/common",
    "core/types",
    "core/treekem",
    "core/ecalls",
    "example/erc20/api",
    "example/erc20/cli",
    "example/erc20/enclave",
    "example/erc20/server",
    "example/erc20/state-transition",
    "example/invoice-flow/api",
    "example/invoice-flow/enclave",
    "example/invoice-flow/server",
    "example/invoice-flow/state-transition",
    "wallet",
    "tests/integration",
    "tests/units/enclave",
    "tests/units/host",
]
