version: '3'
services:
  sgx_machine1:
    image: anonify-server:latest
    devices:
      - "/dev/sgx"
    working_dir: /root/anonify/example/server/
    environment:
      ANONIFY_URL: 172.28.1.1:8080
      ETH_URL: http://172.28.1.2:8545
      ANONYMOUS_ASSET_ABI_PATH: "../../build/Anonify.abi"
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  ganache1:
      image: trufflesuite/ganache-cli:latest
      ports:
        - "8545:8545"
      volumes:
        - ./ganache_data:/ganache_data
      networks:
        testing_net:
          ipv4_address: 172.28.1.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
