version: "3.7"
services:
  sgx_machine:
    image: osuketh/anonify:1804-1.1.3
    volumes:
      - .:/root/anonify
      - /var/run/aesmd:/var/run/aesmd
    devices:
      - "/dev/sgx/enclave"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      SPID: ${SPID}
      SUB_KEY: ${SUB_KEY}
      MY_ROSTER_IDX: ${MY_ROSTER_IDX}
      MAX_ROSTER_IDX: ${MAX_ROSTER_IDX}
      IAS_URL: ${IAS_URL}
      KEY_VAULT_ENDPOINT_FOR_STATE_RUNTIME: "${KEY_VAULT_FQDN}:${KEY_VAULT_PORT}"
      KEY_VAULT_ENDPOINT_FOR_KEY_VAULT: "${KEY_VAULT_IP_ADDRESS}:${KEY_VAULT_PORT}"
      ENCLAVE_PKG_NAME: ${ENCLAVE_PKG_NAME}
      STATE_RUNTIME_ENCLAVE_PKG_NAME: ${STATE_RUNTIME_ENCLAVE_PKG_NAME}
      KEY_VAULT_ENCLAVE_PKG_NAME: ${KEY_VAULT_ENCLAVE_PKG_NAME}
      BACKUP: ${BACKUP}
      ETH_URL: "http://${ETH_ADDRESS}:${ETH_PORT}"
      STATE_RUNTIME_URL: "${STATE_RUNTIME_IP_ADDRESS}:${STATE_RUNTIME_PORT}"
      ABI_PATH: ${ABI_PATH}
      BIN_PATH: ${BIN_PATH}
      CONFIRMATIONS: ${CONFIRMATIONS}
      ACCOUNT_INDEX: ${ACCOUNT_INDEX}
      PASSWORD: ${PASSWORD}
      REQUEST_RETRIES: ${REQUEST_RETRIES}
      RETRY_DELAY_MILLS: ${RETRY_DELAY_MILLS}
      PATH_SECRETS_DIR: ${PATH_SECRETS_DIR}
      IAS_ROOT_CERT_PATH: ${IAS_ROOT_CERT_PATH}
      EVENT_LIMIT: ${EVENT_LIMIT}
      UNLOCK_DURATION: ${UNLOCK_DURATION}
    extra_hosts:
      - "${KEY_VAULT_FQDN}:${KEY_VAULT_IP_ADDRESS}"
    stdin_open: true
    tty: true
    networks:
      testing_net:
        ipv4_address: ${STATE_RUNTIME_IP_ADDRESS}

  ganache:
      image: trufflesuite/ganache-cli:latest
      ports:
        - "${ETH_HOST_PORT}:${ETH_PORT}"
      volumes:
        - ./ganache_data:/ganache_data
      networks:
        testing_net:
          ipv4_address: ${ETH_ADDRESS}

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: ${COMPOSE_NETWORK_SUBNET}