version: "3.7"
services:
  sgx_machine:
    image: anonify.azurecr.io/anonify-dev:latest
    volumes:
      - .:/home/anonify-dev/anonify
      - /var/run/aesmd:/var/run/aesmd
    devices:
      - "/dev/sgx/enclave"
    user: "${UID}:${GID}"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      SPID: ${SPID}
      SUB_KEY: ${SUB_KEY}
      MY_ROSTER_IDX: ${MY_ROSTER_IDX}
      MAX_ROSTER_IDX: ${MAX_ROSTER_IDX}
      IAS_URL: ${IAS_URL}
      KEY_VAULT_ENDPOINT_FOR_STATE_RUNTIME: "${KEY_VAULT_FQDN}:${KEY_VAULT_PORT}"
      KEY_VAULT_ENDPOINT_FOR_KEY_VAULT: "${KEY_VAULT_IP_ADDRESS}:${KEY_VAULT_PORT}"
      ENCLAVE_PKG_NAME: ${ENCLAVE_PKG_NAME}
      STATE_RUNTIME_ENCLAVE_PKG_NAME: ${STATE_RUNTIME_ENCLAVE_PKG_NAME}
      KEY_VAULT_ENCLAVE_PKG_NAME: ${KEY_VAULT_ENCLAVE_PKG_NAME}
      BACKUP: ${BACKUP}
      ETH_URL: "http://${ETH_IP_ADDRESS}:${ETH_DOCKER_PORT}"
      MY_NODE_URL: "${STATE_RUNTIME_IP_ADDRESS}:${STATE_RUNTIME_PORT}"
      ANONIFY_ABI_PATH: ${ANONIFY_ABI_PATH}
      ANONIFY_BIN_PATH: ${ANONIFY_BIN_PATH}
      FACTORY_ABI_PATH: ${FACTORY_ABI_PATH}
      FACTORY_BIN_PATH: ${FACTORY_BIN_PATH}
      CONFIRMATIONS: ${CONFIRMATIONS}
      ACCOUNT_INDEX: ${ACCOUNT_INDEX}
      PASSWORD: ${PASSWORD}
      REQUEST_RETRIES: ${REQUEST_RETRIES}
      RETRY_DELAY_MILLS: ${RETRY_DELAY_MILLS}
      CMD_DEC_SECRET_DIR: ${CMD_DEC_SECRET_DIR}
      IAS_ROOT_CERT_PATH: ${IAS_ROOT_CERT_PATH}
      EVENT_LIMIT: ${EVENT_LIMIT}
      UNLOCK_DURATION: ${UNLOCK_DURATION}
      PJ_ROOT_DIR: ${PJ_ROOT_DIR}
      PJ_NAME: anonify  # TODO: rm PJ_NAME (deprecated) after anonify-contracts stop using it.
      AZURITE_IP_ADDRESS: ${AZURITE_IP_ADDRESS}
    # Add an lookup from the IP Adress to FQDN because of the following limitation of rustls
    # https://github.com/ctz/rustls/issues/184
    # https://github.com/briansmith/webpki/issues/54
    extra_hosts:
      - "${KEY_VAULT_FQDN}:${KEY_VAULT_IP_ADDRESS}"
    stdin_open: true
    tty: true
    networks:
      testing_net:
        ipv4_address: ${STATE_RUNTIME_IP_ADDRESS}

  ganache:
      image: trufflesuite/ganache-cli:latest
      ports:
        - "${ETH_HOST_PORT}:${ETH_DOCKER_PORT}"
      volumes:
        - ./ganache_data:/ganache_data
      networks:
        testing_net:
          ipv4_address: ${ETH_IP_ADDRESS}

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "${AZURITE_BLOB_HOST_PORT}:10000"
      - "${AZURITE_TABLE_HOST_PORT}:10002"
    command: ["azurite", "-L", "-l", "/data", "--blobHost", "0.0.0.0","--queueHost", "0.0.0.0", "--tableHost", "0.0.0.0", "-d", "/data/debug.log", "--skipApiVersionCheck"]
    volumes:
      - ./frame/azure-client/testdata:/data
    networks:
        testing_net:
          ipv4_address: ${AZURITE_IP_ADDRESS}

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: ${COMPOSE_NETWORK_SUBNET}
