version: '3'
services:
  sgx_machine:
    image: osuketh/anonify:latest
    command: cd example/server && cargo run
    environment:
      ANONIFY_URL: 172.28.1.1:8080
      ETH_URL: 172.28.1.2:8545
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  ganache:
      image: trufflesuite/ganache-cli:latest
      ports:
        - "8545:8545"
      volumes:
        - ./ganache_data:/ganache_data
      environment:
        ANONIFY_URL: 172.28.1.1:8080
      entrypoint:
        - node
        - ./build/cli.node.js
        - --deterministic
        - --db=/ganache_data
        - --mnemonic
        - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
        - --networkId
        - '5777'
        - --hostname
        - '0.0.0.0'
        - --debug
      networks:
        testing_net:
          ipv4_address: 172.28.1.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
