version: "3.7"
services:
  sgx_machine:
    image: osuketh/anonify:1804-1.1.3
    volumes:
      - .:/root/anonify
      - /var/run/aesmd:/var/run/aesmd
    devices:
      - "/dev/sgx/enclave"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      SPID: ${SPID}
      SUB_KEY: ${SUB_KEY}
      MY_ROSTER_IDX: ${MY_ROSTER_IDX}
      MAX_ROSTER_IDX: ${MAX_ROSTER_IDX}
      IAS_URL: ${IAS_URL}
      KEY_VAULT_ENDPOINT: ${KEY_VAULT_ENDPOINT}
      AUDITOR_ENDPOINT: ${AUDITOR_ENDPOINT}
      MY_ENCLAVE_PKG_NAME: ${MY_ENCLAVE_PKG_NAME}
      CONNECTED_ENCLAVE_PKG_NAME: ${CONNECTED_ENCLAVE_PKG_NAME}
      BACKUP: ${BACKUP}
      ETH_URL: ${ETH_URL}
      ANONIFY_URL: ${ANONIFY_URL}
      ABI_PATH: ${ABI_PATH}
      BIN_PATH: ${BIN_PATH}
      CONFIRMATIONS: ${CONFIRMATIONS}
      ACCOUNT_INDEX: ${ACCOUNT_INDEX}
      PASSWORD: ${PASSWORD}
      REQUEST_RETRIES: ${REQUEST_RETRIES}
      RETRY_DELAY_MILLS: ${RETRY_DELAY_MILLS}
      PATH_SECRETS_DIR: ${PATH_SECRETS_DIR}
      IAS_ROOT_CERT_PATH: ${IAS_ROOT_CERT_PATH}
    stdin_open: true
    tty: true
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  ganache:
      image: trufflesuite/ganache-cli:latest
      ports:
        - "8545:8545"
      volumes:
        - ./ganache_data:/ganache_data
      networks:
        testing_net:
          ipv4_address: 172.28.0.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16