version: "3.7"
services:
  enclave:
    image: anonify.azurecr.io/base-occlum:latest
    volumes:
      - .:/root/anonify
      - /var/run/aesmd:/var/run/aesmd
    devices:
      - "/dev/sgx/enclave"
    ports:
        - ${DOCKER_ENCLAVE_PORT}:${HOST_PORT}
    environment:
      SPID: ${SPID}
      SUB_KEY: ${SUB_KEY}
      IAS_URL: ${IAS_URL}
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      OCCLUM_LOG_LEVEL: debug
    stdin_open: true
    tty: true
    networks:
      osuke2_testing_net:
        ipv4_address: ${DOCKER_ENCLAVE_IP_ADDRESS}

  host:
    image: rust:1.52.1
    volumes:
      - .:/root/anonify
    ports:
      - ${DOCKER_HOST_PORT}:${HOST_PORT}
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      OCCLUM_LOG_LEVEL: debug
    stdin_open: true
    tty: true
    networks:
      osuke2_testing_net:
        ipv4_address: ${DOCKER_HOST_IP_ADDRESS}

networks:
  occlum_testing_net:
    ipam:
      driver: default
      config:
        - subnet: ${COMPOSE_NETWORK_SUBNET}
