[package]
name = "invoice-enclave"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[lib]
name = "anonifyenclave"
crate-type = ["staticlib"]

[dependencies]
config = { path = "../../../config", default-features = false, features = ["sgx"]}
frame-enclave = { path = "../../../frame/enclave" }
frame-types = { path = "../../../frame/types" }
anonify-enclave = { path = "../../../core/enclave" }
frame-treekem = { path = "../../../frame/treekem" }
frame-common = { path = "../../../frame/common", default-features = false, features = ["sgx"] }
invoice-state-transition = { path = "../state-transition", default-features = false, features = ["sgx"] }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git"}
lazy_static = { version = "1.4", features = ["spin_no_std"] }
ed25519-dalek = { version = "1.0.0-pre.2", default-features = false, features = ["u64_backend"] }
sgx_types = "1.1.1"
codec = { package = "parity-scale-codec", version = "1.1", default-features = false }
log = { rev = "sgx_1.1.2", git = "https://github.com/mesalock-linux/log-sgx" }
anyhow = { rev = "sgx_1.1.2", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
