[package]
name = "encrypted-sql-ops-enclave"
version = "0.1.0"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net","backtrace"] }
frame-config = { path = "../../frame/config", default-features = false, features = ["sgx"] }
frame-common = { path = "../../frame/common", default-features = false, features = ["sgx"] }
encrypted-sql-ops-ecall-types = { path = "../encrypted-sql-ops-ecall-types" }
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git" } # Don't specify version due to serde_json dependency
aes = "0.7.2"
thiserror = { git = "https://github.com/mesalock-linux/thiserror-sgx.git" }
