[package]
name = "anonify-common"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = { version = "1.0.0-pre.2", default-features = false, features = ["u64_backend"] }
sha2 = { version = "0.8", default-features = false }
tiny-keccak = "1.4"
serde-std = { package = "serde", version = "1", default-features = false, optional = true }
serde-sgx = { package = "serde", git = "https://github.com/mesalock-linux/serde-sgx.git", rev = "sgx_1.0.9", default-features = false, optional = true }
sgx_tstd = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }
base64 = { version = "0.11", optional = true }
web3 = { version = "0.8", optional = true }
rand = { version = "0.6", optional = true }
rand_core = { version = "0.3", optional = true }
sgx-elastic-array = { package = "elastic-array", version = "0.10", git = "https://github.com/mesalock-linux/elastic-array-sgx.git", optional = true }
elastic-array = { version = "0.10", optional = true }
byteorder = { version = "1", default-features = false }

[features]
default = ["std"]
std = [
    "serde-std/std",
    "serde-std/derive",
    "base64",
    "web3",
    "rand",
    "rand_core",
    "elastic-array"
]
sgx = [
    "sgx_tstd",
    "serde-sgx",
    "serde-sgx/derive",
    "sgx-elastic-array"
]
