[package]
name = "anonify-common"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sgx_tstd = { git = "https://github.com/apache/mesatee-sgx", rev = "v1.0.9", optional = true }
sgx_trts = { git = "https://github.com/apache/mesatee-sgx", rev = "v1.0.9", optional = true }
sgx_types = { git = "https://github.com/apache/mesatee-sgx", rev = "v1.0.9", optional = true }

[features]
default = ["std"]
std = []
sgx = ["sgx_tstd", "sgx_trts", "sgx_types"]
