[package]
name = "erc20-enclave"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[lib]
name = "anonifyenclave"
crate-type = ["staticlib"]

[dependencies]
anonify-enclave = { path = "../../../core/enclave", features = ["erc20"] }
anonify-common = { path = "../../../core/common", default-features = false, features = ["sgx"] }
anonify-runtime = { path = "../../../core/runtime", default-features = false, features = ["sgx"] }
anonify-types = { path = "../../../core/types", default-features = false }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git"}
codec = { package = "parity-scale-codec", version = "1.1", default-features = false, features = ["derive"] }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
