[package]
name = "erc20-enclave"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[lib]
name = "anonifyenclave"
crate-type = ["staticlib"]

[dependencies]
anonify-config = { path = "../../../config", default-features = false, features = ["sgx"]}
frame-enclave = { path = "../../../frame/enclave" }
frame-types = { path = "../../../frame/types" }
frame-treekem = { path = "../../../frame/treekem", default-features = false, features = ["sgx"] }
frame-common = { path = "../../../frame/common", default-features = false, features = ["sgx"] }
anonify-enclave = { path = "../../../modules/anonify-enclave", default-features = false }
erc20-state-transition = { path = "../state-transition", default-features = false, features = ["sgx"] }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git"}
lazy_static = { version = "1.4", features = ["spin_no_std"] }
ed25519-dalek = { version = "1.0.0-pre.2", default-features = false, features = ["u64_backend"] }
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
codec = { package = "parity-scale-codec", version = "1.1", default-features = false }
log = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/log-sgx" }
anyhow = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }

[features]
default = ["backup-enable", "runtime_enabled"]
backup-enable = ["anonify-enclave/backup-enable"]
runtime_enabled = []
