[package]
name = "frame-mra-tls"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
remote-attestation = { path = "../remote-attestation" }
anonify-config = { path = "../../config", default-features = false, features = ["sgx"] } # Only used tests to use IAS_ROOT_CERT
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net", "backtrace", "thread"] }
sgx_tcrypto = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
rustls = { branch = "mesalock_sgx", version = "^0.19", git = "https://github.com/mesalock-linux/rustls", features = ["dangerous_configuration"] }
anyhow = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
thiserror = { git = "https://github.com/mesalock-linux/thiserror-sgx.git" }
codec = { package = "parity-scale-codec", version = "1.1", default-features = false }
serde_json = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/serde-json-sgx" }
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git" } # Don't specify version due to serde_json dependency
http = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/http-sgx" }
webpki = { branch = "mesalock_sgx", git = "https://github.com/mesalock-linux/webpki" } # Specify branch name due to rustls dependency
webpki-roots = { branch = "mesalock_sgx", git = "https://github.com/mesalock-linux/webpki-roots" }
log = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/log-sgx" }
once_cell = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/once_cell-sgx" }
yasna = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/yasna.rs-sgx", features = ["bit-vec", "num-bigint", "chrono"] }
bit-vec = { version = "0.6.1", default-features = false }
num-bigint = { version = "0.2", git = "https://github.com/mesalock-linux/num-bigint-sgx" }
chrono = { version = "0.4", git = "https://github.com/mesalock-linux/chrono-sgx" }
test-utils = { path = "../../tests/utils" }
pem = { version = "0.8.2", git = "https://github.com/mesalock-linux/pem-rs-sgx" }
