[package]
name = "mra-tls"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net","backtrace"] }
rustls = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/rustls" }
