[package]
name = "erc20-cli"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
erc20-api = { path = "../api" }
frame-common = { path = "../../../frame/common" }
frame-ecies = { path = "../../../frame/ecies" }
anonify-wallet = { path = "../../../wallet" }
reqwest = "0.9"
clap = "~2.32"
rand = "0.7"
console = "0.7"
dialoguer = "0.4"
dirs = "2.0"
log = "0.4"
env_logger = "0.7"
tiny-bip39 = "0.6.0"
ed25519-dalek = "1.0.0-pre.2"
web3 = "0.14"
ethabi = "12.0.0"
anyhow = "1.0"
thiserror = "1.0"
serde_json = "1.0"
