[package]
name = "state-runtime-node-api"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
frame-sodium = { path = "../../../frame/sodium" }
serde = { version = "1", features = ["derive"] }
web3 = { version = "0.14.0", default-features = false, features = ["http-tls"] }
serde_json = "1.0"
