[package]
name = "state-runtime-node-api"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
frame-sodium = { path = "../../../frame/sodium" }
frame-common = { path = "../../../frame/common" }
serde = { version = "1", features = ["derive"] }
web3 = "0.14"
serde_json = "1.0"
