[package]
name = "erc20-api"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
frame-treekem = { path = "../../../frame/treekem" }
serde = { version = "1", features = ["derive"] }
web3 = "0.14"
serde_json = "1.0"
