[package]
name = "erc20-api"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
frame-common = { path = "../../../frame/common" }
serde = { version = "1", features = ["derive"] }
ed25519-dalek = { version = "1.0.0-pre.2", features = ["serde"] }
rand = "0.7"
serde-big-array = "0.2"
web3 = "0.11"
