[package]
name = "secret-backup-server"
version = "0.1.0"
authors = ["cipepser <respepic@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-rt = "1.1"
anyhow = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
rustls = "0.19.0"
sgx_types = "1.1.1"
tracing = "0.1"
tracing-subscriber = "0.2"
key-vault-commands = { path = "../commands"}
frame-host = { path = "../../../frame/host" }
key-vault-host = { path = "../../../modules/key-vault-host" }
once_cell = "1.5.2"

[dev-dependencies]
frame-config = { path = "../../../frame/config" }
frame-common = { path = "../../../frame/common" }
frame-runtime = { path = "../../../frame/runtime" }
frame-sodium = { path = "../../../frame/sodium" }
erc20-server = { path = "../../erc20/server" }
erc20-api = { path = "../../erc20/api" }
anonify-eth-driver = { path = "../../../modules/anonify-eth-driver" }
anonify-ecall-types = { path = "../../../modules/anonify-ecall-types"}
erc20-server = { path = "../../../example/erc20/server" }
erc20-api = { path = "../../../example/erc20/api" }
web3 = "0.14"
ethabi = "12.0.0"
sgx_urts = "1.1.1"
rand_core = "0.5"
rand = "0.7"