version: 2.1
jobs:
  build:
    docker:
      - image: osuketh/anonify:latest
    steps:
      - checkout
      - run:
        name: core-make
        command: cd core && RUSTFLAGS=-Awarnings make DEBUG=1
      - run:
        name: core-test
        command: cd app && cargo test
# TODO: Device bindings
