version: 2.1
jobs:
  build:
    docker:
      - image: osuketh/anonify:latest
    working_directory: ~/anonify
    steps:
      - checkout
      - run: . /opt/sgxsdk/environment
      - run: cp .env.template .env && cp example/server/.env.template example/server/.env
      - run:
          name: Building contracts
          command: solc -o build --bin --abi --optimize --overwrite contracts/AnonymousAsset.sol
      - run:
          name: Building all
          command: |
            export PATH=~/.cargo/bin:$PATH
            ./scripts/build-all.sh
