version: 2.1
jobs:
  build:
    docker:
      - image: osuketh/anonify:latest
    steps:
      - checkout
      - run: LD_LIBRARY_PATH=/opt/intel/libsgx-enclave-common/aesm /opt/intel/libsgx-enclave-common/aesm/aesm_service
      - run: . /opt/sgxsdk/environment
      - run: /root/.cargo/bin/cargo --version
      - run:
          name: Building contracts
          command: solc -o build --bin --abi --optimize --overwrite contracts/AnonymousAsset.sol
      - run:
          name: root tests
          command: /root/.cargo/bin/cargo test --all
      # - run:
      #     name: server build
      #     command: cd example/server && /root/.cargo/bin/cargo build
      #     no_output_timeout: 30m
      # - run:
      #     name: core-make
      #     command: cd core && RUSTFLAGS=-Awarnings CARGO=/root/.cargo/bin/cargo BINDGEN=/root/.cargo/bin/bindgen RUSTFMT=/root/.cargo/bin/rustfmt make DEBUG=1
      # - run:
      #     name: core-test
      #     command: cd host && /root/.cargo/bin/cargo test -- --nocapture
