[package]
name = "anonify-ecall-types"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
frame-common = { path = "../../frame/common", default-features = false }
frame-runtime = { path = "../../frame/runtime", default-features = false }
frame-treekem = { path = "../../frame/treekem", default-features = false }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
codec = { package = "parity-scale-codec", version = "1.1", default-features = false, features = ["derive"] }
libsecp256k1 = { version = "0.2", default-features = false }
hex = { version = "0.4", default-features = false }

[features]
default = ["std"]
std = [
    "frame-common/std",
    "frame-runtime/std",
    "frame-treekem/std",
]
sgx = [
    "frame-common/sgx",
    "frame-runtime/sgx",
    "frame-treekem/sgx",
    "sgx_tstd",
]
