[package]
name = "frame-host"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
frame-types = { path = "../../frame/types" }
frame-common = { path = "../../frame/common" }
anyhow = "1.0"
thiserror = "1.0"
sgx_types = "1.1.1"
sgx_urts = "1.1.1"
codec = { package = "parity-scale-codec", version = "1.1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
dirs = "2.0"
log = "0.4"
lazy_static = "1.4"
hex = "0.4"
once_cell = "1.5.2"

[build-dependencies]
dirs = "2.0"
cc = "1.0"
