[package]
name = "erc20-server"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
erc20-api = { path = "../api" }
erc20-state-transition = { path = "../state-transition" }
anonify-eth-driver = { path = "../../../modules/anonify-eth-driver" }
frame-host = { path = "../../../frame/host" }
frame-runtime = { path = "../../../frame/runtime" }
frame-common = { path = "../../../frame/common" }
sgx_types = "1.1.1"
actix-web = "3"
actix-rt = "1.1"
failure = "0.1"
tracing = "0.1"
tracing-subscriber = "0.2"
hex = "0.4"
anyhow = "1.0"
web3 = { git = "https://github.com/tomusdrw/rust-web3", rev = "d7393708e257f7ef4ad354917889a8001cf2927c" }
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
integration-tests = { path = "../../../tests/integration" }
frame-runtime = { path = "../../../frame/runtime" }
frame-treekem = { path = "../../../frame/treekem" }
web3 = { git = "https://github.com/tomusdrw/rust-web3", rev = "d7393708e257f7ef4ad354917889a8001cf2927c" }
ethabi = "12.0.0"
codec = { package = "parity-scale-codec", version = "1.1" }
