[package]
name = "erc20-server"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
erc20-api = { path = "../api" }
erc20-state-transition = { path = "../state-transition" }
anonify-host = { path = "../../../core/host" }
frame-host = { path = "../../../frame/host" }
frame-runtime = { path = "../../../frame/runtime" }
sgx_types = "1.1.1"
actix-web = "1.0"
failure = "0.1"
log = "0.4"
env_logger = "0.7"
ed25519-dalek = "1.0.0-pre.2"
hex = "0.4"
anyhow = "1.0"
