[package]
name = "erc20-server"
version = "0.5.2"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
state-runtime-node-server = { path = "../../../nodes/state-runtime/server", default-features = false }
anonify-eth-driver = { path = "../../../modules/anonify-eth-driver", default-features = false }
frame-host = { path = "../../../frame/host" }
actix-web = "3"
failure = "0.1"
tracing-subscriber = "0.2"

[features]
default = ["backup-enable"]
backup-enable = [
    "state-runtime-node-server/backup-enable",
    "anonify-eth-driver/backup-enable",
]
