[package]
name = "anonify-server"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
api = { path = "../api" }
anonify-common = { path = "../../../core/common" }
anonify-runtime = { path = "../../../core/runtime" }
anonify-host = { path = "../../../core/host" }
anonify-bc-connector = { path = "../../../core/bc-connector" }
erc20-state-transition = { path = "../state-transition", default-features = false, features = ["std"] }
sgx_types = "1.1.1"
actix-web = "1.0"
failure = "0.1"
log = "0.4"
env_logger = "0.7"
ed25519-dalek = "1.0.0-pre.2"
hex = "0.4"
anyhow = "1.0"
