[package]
name = "erc20-server"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
anonify-node-server = { path = "../../../nodes/anonify/server", default-features = false }
anonify-eth-driver = { path = "../../../modules/anonify-eth-driver", default-features = false }
frame-host = { path = "../../../frame/host" }
actix-web = "3"
failure = "0.1"
tracing-subscriber = "0.2"

[features]
default = ["backup-enable"]
backup-enable = [
    "anonify-node-server/backup-enable",
    "anonify-eth-driver/backup-enable",
]
