[package]
name = "frame-treekem"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
anonify-config = { path = "../../config", default-features = false, features = ["sgx"], optional = true}
frame-config = { path = "../config", default-features = false }
frame-common = { path = "../common", default-features = false }
frame-mra-tls = { path = "../../frame/mra-tls", optional = true }
test-utils = { path = "../../tests/utils", optional = true }
anyhow = { version = "1.0", optional = true }
hex = { version = "0.4", default-features = false }
sgx-anyhow = { rev = "sgx_1.1.3", package = "anyhow", git = "https://github.com/mesalock-linux/anyhow-sgx.git", optional = true }
std-libsecp256k1 = { package = "libsecp256k1", git = "https://github.com/paritytech/libsecp256k1.git", rev = "12e3829d6cd2d6459c2c920d7cf222f3a930b955", optional = true }
sgx-libsecp256k1 = { package = "libsecp256k1", rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/libsecp256k1-rs-sgx", optional = true }
std_rand = { package = "rand", version = "0.6", optional = true }
sgx_rand = { package = "rand", rev = "v0.7.3_sgx1.1.3", git = "https://github.com/mesalock-linux/rand-sgx", optional = true }
std_rand_core = { package = "rand_core", version = "0.3", optional = true }
sgx_rand_core = { package = "rand_core", rev = "v0.7.3_sgx1.1.3", git = "https://github.com/mesalock-linux/rand-sgx", optional = true }
std-ring = { package = "ring", version = "0.16.15", optional = true }
sgx-ring = { package = "ring", git = "https://github.com/mesalock-linux/ring-sgx", tag = "v0.16.5", optional = true }
codec = { package = "parity-scale-codec", version = "1.1", default-features = false }
std-log = { package = "log", version = "0.4", optional = true }
sgx-log = { package = "log", rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/log-sgx", optional = true }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net", "backtrace"], optional = true }
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_tseal = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
serde-std = { package = "serde", version = "1", default-features = false, optional = true }
serde-sgx = { package = "serde", git = "https://github.com/mesalock-linux/serde-sgx.git", default-features = false, optional = true, features = ["derive"] }
serde_json = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/serde-json-sgx", optional = true }

[features]
default = ["std"]
std = [
    "frame-common/std",
    "anyhow",
    "std-libsecp256k1",
    "std_rand",
    "std_rand_core",
    "std-ring",
    "std-log",
    "serde-std/std",
    "serde-std/derive",
]
sgx = [
    "anonify-config",
    "frame-mra-tls",
    "frame-common/sgx",
    "test-utils",
    "sgx-anyhow",
    "sgx-libsecp256k1",
    "sgx_rand",
    "sgx_rand_core",
    "sgx-ring",
    "sgx-log",
    "sgx_tstd",
    "sgx_types",
    "sgx_tseal",
    "serde-sgx",
    "serde-sgx/derive",
    "serde_json",
]