[package]
name = "frame-treekem"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
frame-common = { path = "../common", default-features = false, features = ["sgx"] }
test-utils = { path = "../../tests/utils" }
anyhow = { rev = "sgx_1.1.2", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
libsecp256k1 = { rev = "sgx_1.1.2", git = "https://github.com/mesalock-linux/libsecp256k1-rs-sgx" }
rand = { rev = "v0.6.5_sgx1.1.2", git = "https://github.com/mesalock-linux/rand-sgx"}
rand_core = { rev = "v0.6.5_sgx1.1.2", git = "https://github.com/mesalock-linux/rand-sgx"}
ring = { git = "https://github.com/mesalock-linux/ring-sgx", tag = "v0.16.5" }
codec = { package = "parity-scale-codec", version = "1.1", default-features = false }
log = { rev = "sgx_1.1.2", git = "https://github.com/mesalock-linux/log-sgx" }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net"] }
sgx_types = "1.1.1"
sgx_tseal = "1.1.1"