version: "3.7"

x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:2.2.5}"
  expose:
    - "21000"
    - "50400"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/dd
      rm -rf $${DDIR}
      mkdir -p $${DDIR}/keystore
      mkdir -p $${DDIR}/geth
      cp /examples/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
      cp /examples/keys/key$${NODE_ID} $${DDIR}/keystore/
      cat /examples/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\&raftport=50400\4/g' > $${DDIR}/static-nodes.json
      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
      cat $${DDIR}/static-nodes.json
      GENESIS_FILE="/examples/istanbul-genesis.json"
      if [ "${QUORUM_CONSENSUS:-istanbul}" == "raft" ]; then
        GENESIS_FILE="/examples/genesis.json"
      fi
      NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
      GETH_ARGS_raft="--raft --raftport 50400"
      GETH_ARGS_istanbul="--emitcheckpoints --istanbul.blockperiod 1 --mine --minerthreads 1 --syncmode full"
      geth --datadir $${DDIR} init $${GENESIS_FILE}
      geth \
        --identity node$${NODE_ID}-${QUORUM_CONSENSUS:-istanbul} \
        --datadir $${DDIR} \
        --permissioned \
        --nodiscover \
        --verbosity 5 \
        --networkid $${NETWORK_ID} \
        --rpc \
        --rpcvhosts=* \
        --rpcaddr 0.0.0.0 \
        --rpcport 8545 \
        --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONSENSUS:-istanbul} \
        --port 21000 \
        --unlock 0 \
        --password /examples/passwords.txt \
        ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_${QUORUM_CONSENSUS:-istanbul}}

services:
  sgx_machine1:
    image: osuketh/anonify-server:latest
    volumes:
      # See: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/documents/sgx_in_mesalock_linux.md#solution-overview
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx"
    working_dir: /root/anonify/example/server/
    environment:
      ANONIFY_URL: 172.28.1.1:8080
      ETH_URL: http://172.28.1.11:8545
      ANONYMOUS_ASSET_ABI_PATH: "../../build/Anonify.abi"
      MY_ROSTER_IDX: 0
      MAX_ROSTER_IDX: 2
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  sgx_machine2:
    image: osuketh/anonify-server:latest
    volumes:
      # See: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/documents/sgx_in_mesalock_linux.md#solution-overview
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx"
    working_dir: /root/anonify/example/server/
    environment:
      ANONIFY_URL: 172.28.1.2:8080
      ETH_URL: http://172.28.1.12:8545
      ANONYMOUS_ASSET_ABI_PATH: "../../build/Anonify.abi"
      MY_ROSTER_IDX: 1
      MAX_ROSTER_IDX: 2
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  sgx_machine3:
    image: osuketh/anonify-server:latest
    volumes:
      # See: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/documents/sgx_in_mesalock_linux.md#solution-overview
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx"
    working_dir: /root/anonify/example/server/
    environment:
      ANONIFY_URL: 172.28.1.3:8080
      ETH_URL: http://172.28.1.13:8545
      ANONYMOUS_ASSET_ABI_PATH: "../../build/Anonify.abi"
      MY_ROSTER_IDX: 2
      MAX_ROSTER_IDX: 2
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  quorum_node1:
    << : *quorum-def
    hostname: quorum_node1
    ports:
      - "22000:8545"
    volumes:
      - vol1:/qdata
      - ../.quorum:/examples:ro
    environment:
      - NODE_ID=1
    networks:
      testing_net:
        ipv4_address: 172.28.1.11

  quorum_node2:
    << : *quorum-def
    hostname: quorum_node2
    ports:
      - "22001:8545"
    volumes:
      - vol1:/qdata
      - ../.quorum:/examples:ro
    environment:
      - NODE_ID=2
    networks:
      testing_net:
        ipv4_address: 172.28.1.12

  quorum_node3:
    << : *quorum-def
    hostname: quorum_node3
    ports:
      - "22002:8545"
    volumes:
      - vol1:/qdata
      - ../.quorum:/examples:ro
    environment:
      - NODE_ID=3
    networks:
      testing_net:
        ipv4_address: 172.28.1.13

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  "vol1":
  "vol2":
  "vol3":