version: "3.7"

x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:2.2.5}"
  expose:
    - "21000"
    - "50400"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  entrypoint:
    - /bin/sh
    - -c
    - ./scripts/quorum-node.sh

x-tx-manager-def:
  &tx-manager-def
  image: "${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:0.10.0}"
  expose:
    - "9000"
    - "9080"
  restart: "no"
  healthcheck:
    test: ["CMD-SHELL", "[ -S /qdata/tm/tm.ipc ] || exit 1"]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - ./scripts/quorum-tx-manager.sh

services:
  sgx_machine1:
    image: osuketh/anonify-server:latest
    volumes:
      # See: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/documents/sgx_in_mesalock_linux.md#solution-overview
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx"
    working_dir: /root/anonify/example/server/
    environment:
      ANONIFY_URL: 172.28.1.1:8080
      ETH_URL: http://172.28.1.11:8545
      ANONYMOUS_ASSET_ABI_PATH: "../../build/Anonify.abi"
      MY_ROSTER_IDX: 0
      MAX_ROSTER_IDX: 2
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  sgx_machine2:
    image: osuketh/anonify-server:latest
    volumes:
      # See: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/documents/sgx_in_mesalock_linux.md#solution-overview
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx"
    working_dir: /root/anonify/example/server/
    environment:
      ANONIFY_URL: 172.28.1.2:8080
      ETH_URL: http://172.28.1.12:8545
      ANONYMOUS_ASSET_ABI_PATH: "../../build/Anonify.abi"
      MY_ROSTER_IDX: 1
      MAX_ROSTER_IDX: 2
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  sgx_machine3:
    image: osuketh/anonify-server:latest
    volumes:
      # See: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/documents/sgx_in_mesalock_linux.md#solution-overview
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx"
    working_dir: /root/anonify/example/server/
    environment:
      ANONIFY_URL: 172.28.1.3:8080
      ETH_URL: http://172.28.1.13:8545
      ANONYMOUS_ASSET_ABI_PATH: "../../build/Anonify.abi"
      MY_ROSTER_IDX: 2
      MAX_ROSTER_IDX: 2
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  quorum_node1:
    << : *quorum-def
    hostname: quorum_node1
    ports:
      - "22000:8545"
    volumes:
      - vol1:/qdata
      - ./.quorum:/examples:ro
    depends_on:
      - txmanager1
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=1
    networks:
      testing_net:
        ipv4_address: 172.28.1.11

  txmanager1:
    << : *tx-manager-def
    hostname: txmanager1
    ports:
      - "9081:9080"
    volumes:
      - vol1:/qdata
      - ./.quorum:/examples:ro
    networks:
      testing_net:
        ipv4_address: 172.28.1.101
    environment:
      - NODE_ID=1

  quorum_node2:
    << : *quorum-def
    hostname: quorum_node2
    ports:
      - "22000:8545"
    volumes:
      - vol1:/qdata
      - ./.quorum:/examples:ro
    depends_on:
      - txmanager2
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=2
    networks:
      testing_net:
        ipv4_address: 172.28.1.12

  txmanager2:
    << : *tx-manager-def
    hostname: txmanager2
    ports:
      - "9081:9080"
    volumes:
      - vol1:/qdata
      - ./.quorum:/examples:ro
    networks:
      testing_net:
        ipv4_address: 172.28.1.102
    environment:
      - NODE_ID=2

  quorum_node3:
    << : *quorum-def
    hostname: quorum_node3
    ports:
      - "22000:8545"
    volumes:
      - vol1:/qdata
      - ./.quorum:/examples:ro
    depends_on:
      - txmanager3
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=3
    networks:
      testing_net:
        ipv4_address: 172.28.1.13

  txmanager3:
    << : *tx-manager-def
    hostname: txmanager3
    ports:
      - "9081:9080"
    volumes:
      - vol1:/qdata
      - ./.quorum:/examples:ro
    networks:
      testing_net:
        ipv4_address: 172.28.1.103
    environment:
      - NODE_ID=3

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  "vol1":
  "vol2":
  "vol3":