version: "3.7"
services:
  sgx_machine1:
    image: osuketh/anonify-server:latest
    volumes:
      # See: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/documents/sgx_in_mesalock_linux.md#solution-overview
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx"
    working_dir: /root/anonify/example/server/
    environment:
      ANONIFY_URL: 172.28.1.1:8080
      ETH_URL: http://172.28.1.11:8545
      ANONYMOUS_ASSET_ABI_PATH: "../../build/Anonify.abi"
      MY_ROSTER_IDX: 0
      MAX_ROSTER_IDX: 2
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  sgx_machine2:
    image: osuketh/anonify-server:latest
    volumes:
      # See: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/documents/sgx_in_mesalock_linux.md#solution-overview
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx"
    working_dir: /root/anonify/example/server/
    environment:
      ANONIFY_URL: 172.28.1.2:8080
      ETH_URL: http://172.28.1.11:8545
      ANONYMOUS_ASSET_ABI_PATH: "../../build/Anonify.abi"
      MY_ROSTER_IDX: 1
      MAX_ROSTER_IDX: 2
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  sgx_machine3:
    image: osuketh/anonify-server:latest
    volumes:
      # See: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/documents/sgx_in_mesalock_linux.md#solution-overview
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx"
    working_dir: /root/anonify/example/server/
    environment:
      ANONIFY_URL: 172.28.1.3:8080
      ETH_URL: http://172.28.1.11:8545
      ANONYMOUS_ASSET_ABI_PATH: "../../build/Anonify.abi"
      MY_ROSTER_IDX: 2
      MAX_ROSTER_IDX: 2
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  ganache1:
      image: trufflesuite/ganache-cli:latest
      ports:
        - "8545:8545"
      volumes:
        - ./ganache_data:/ganache_data
      networks:
        testing_net:
          ipv4_address: 172.28.1.11

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
