[package]
name = "key-vault-host"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
anonify-config = { path = "../../config" }
frame-host = { path = "../../frame/host" }
anonify-io-types = { path = "../anonify-io-types" }
parking_lot = "0.10"
rustls = "0.19.0"
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
anyhow = "1.0"
thiserror = "1.0"
