[package]
name = "state-runtime-node-server"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
state-runtime-node-api = { path = "../api" }
anonify-ecall-types = { path = "../../../modules/anonify-ecall-types"}
anonify-eth-driver = { path = "../../../modules/anonify-eth-driver", default-features = false }
frame-host = { path = "../../../frame/host" }
frame-common = { path = "../../../frame/common" }
frame-config = { path = "../../../frame/config" }
sgx_types = "1.1.1"
actix-web = "3"
actix-rt = "1.1"
failure = "0.1"
tracing = "0.1"
tracing-subscriber = "0.2"
hex = "0.4"
anyhow = "1.0"
web3 = "0.14"
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
integration-tests = { path = "../../../tests/integration" }
frame-runtime = { path = "../../../frame/runtime" }
frame-sodium = { path = "../../../frame/sodium" }
anonify-ecall-types = { path = "../../../modules/anonify-ecall-types"}
ethabi = "12.0.0"
rand_core = "0.5"
rand = "0.7"

[features]
default = ["backup-enable"]
backup-enable = [
    "anonify-eth-driver/backup-enable",
]
