[package]
name = "enc"
version = "0.1.0"
authors = ["cipepser <respepic@gmail.com>"]
edition = "2018"


[dependencies]
frame-sodium = { path = "../../frame/sodium" }
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
