[package]
name = "frame-retrier"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
tracing = { version = "0.1", default-features = false }

[features]
default = ["std"]
std = []
sgx = [
    "sgx_tstd",
]
