[package]
name = "frame-retrier"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
tracing = { version = "0.1", default-features = false }
actix-rt = { version = "1.1", optional = true }
tokio = { version = "1.6", optional = true, features = ["time"] }

[features]
default = ["std"]
std = [
    "actix-rt",
    "tokio",
]
sgx = [
    "sgx_tstd",
]
