[package]
name = "secret-backup-server"
version = "0.1.0"
authors = ["cipepser <respepic@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-rt = "1.1"
anyhow = "1.0"
serde_json = "1.0"
thiserror = "1.0"
rustls = "0.19.0"
sgx_types = "1.1.1"
tracing = "0.1"
tracing-subscriber = "0.2"
frame-host = { path = "../../../frame/host" }
key-vault-host = { path = "../../../modules/key-vault-host" }
secret-backup-api = { path = "../api" }
once_cell = "1.5.2"

[dev-dependencies]
anonify-config = { path = "../../../config" }
frame-common = { path = "../../../frame/common" }
frame-runtime = { path = "../../../frame/runtime" }
frame-treekem = { path = "../../../frame/treekem" }
erc20-state-transition = { path = "../../erc20/state-transition" }
anonify-eth-driver = { path = "../../../modules/anonify-eth-driver" }
codec = { package = "parity-scale-codec", version = "1.1" }
web3 = { git = "https://github.com/tomusdrw/rust-web3", rev = "d7393708e257f7ef4ad354917889a8001cf2927c" }
ethabi = "12.0.0"
