
[runtime]
max_mem_size = 100
ciphertext_size = 130

[commands]
encrypt_instruction = 1
insert_ciphertext = 2
insert_handshake = 3
get_state = 4
call_join_group = 5
call_handshake = 6
register_notification = 7
