[package]
name = "key-vault-ecall-types"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
frame-common = { path = "../../frame/common", default-features = false }
serde-std = { package = "serde", version = "1", default-features = false, optional = true }
serde-sgx = { package = "serde", git = "https://github.com/mesalock-linux/serde-sgx.git", default-features = false, optional = true, features = ["derive"] }

[features]
default = ["std"]
std = [
    "frame-common/std",
    "serde-std",
]
sgx = [
    "frame-common/sgx",
    "serde-sgx",
]
