[package]
name = "invoice-app"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
anonify-runtime = { path = "../../../core/runtime" }
anonify-common = { path = "../../../core/common", default-features = false, features = ["sgx"] }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
codec = { package = "parity-scale-codec", version = "1.1", default-features = false, features = ["derive"] }
