[package]
name = "frame-sodium"
version = "0.5.3"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
frame-common = { path = "../common", default-features = false }
frame-config = { path = "../config", default-features = false, features = ["sgx"], optional = true }
anyhow = { version = "1.0", optional = true }
sgx-anyhow = { rev = "sgx_1.1.3", package = "anyhow", git = "https://github.com/mesalock-linux/anyhow-sgx.git", optional = true }
std_rand_core = { version = "0.5", package = "rand_core", optional = true }
sgx_rand_core = { package = "rand_core", branch = "feature/only-trait", git = "https://github.com/cipepser/rand", default-features = false, optional = true }
sgx_trts = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net","backtrace"], optional = true }
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_crypto_box = { package = "crypto_box", branch = "feature/no-default-feature-in-rand-core", git = "https://github.com/cipepser/AEADs.git", optional = true }
std_crypto_box = { package = "crypto_box", version = "0.5.0", optional = true }
sgx_xsalsa20poly1305 = { package = "xsalsa20poly1305", branch = "feature/no-default-feature-in-rand-core", git = "https://github.com/cipepser/AEADs.git", optional = true }
std_xsalsa20poly1305 = { package = "xsalsa20poly1305", version = "0.6.0", optional = true }
rand = { version = "0.7", optional = true }
bincode-std = { package = "bincode", version = "1.3", optional = true }
bincode-sgx = { package = "bincode", git = "https://github.com/mesalock-linux/bincode-sgx", optional = true }
serde-std = { package = "serde", version = "1", default-features = false, optional = true }
serde-sgx = { package = "serde", git = "https://github.com/mesalock-linux/serde-sgx.git", default-features = false, optional = true, features = ["derive"] }
serde_bytes_std = { package = "serde_bytes", version = "0.11", optional = true }
serde_bytes_sgx = { package = "serde_bytes", git = "https://github.com/mesalock-linux/serde-bytes-sgx", optional = true }
sgx_tseal = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
tracing = { version = "0.1", default-features = false }
serde_json_sgx = { package = "serde_json", rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/serde-json-sgx", optional = true }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
std = [
    "frame-common/std",
    "anyhow",
    "rand",
    "std_rand_core",
    "std_crypto_box",
    "std_xsalsa20poly1305",
    "bincode-std",
    "serde-std/std",
    "serde-std/derive",
    "serde_bytes_std",
]
sgx = [
    "frame-common/sgx",
    "frame-config",
    "sgx-anyhow",
    "sgx_rand_core",
    "sgx_trts",
    "sgx_tstd",
    "sgx_types",
    "sgx_crypto_box",
    "sgx_xsalsa20poly1305",
    "serde-sgx",
    "serde-sgx/derive",
    "serde_bytes_sgx",
    "bincode-sgx",
    "sgx_tseal",
    "serde_json_sgx",
]
