[package]
name = "anonify-eth-driver"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
frame-types = { path = "../../frame/types" }
frame-common = { path = "../../frame/common" }
frame-treekem = { path = "../../frame/treekem" }
frame-runtime = { path = "../../frame/runtime" }
frame-host = { path = "../../frame/host" }
frame-retrier = { path = "../../frame/retrier" }
frame-config = { path = "../../frame/config" }
anonify-ecall-types = { path = "../anonify-ecall-types" }
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
thiserror = "1.0"
anyhow = "1.0"
ed25519-dalek = "1.0.0-pre.2"
parking_lot = "0.10"
web3 = "0.14"
ethabi = "12.0.0"
hex = "0.4"
async-trait = "0.1"
tracing = "0.1"
serde_json = "1.0"

[features]
default = ["backup-enable"]
backup-enable = []