[package]
name = "anonify-eth-driver"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
config = { path = "../../config" }
frame-types = { path = "../../frame/types" }
frame-common = { path = "../../frame/common" }
frame-host = { path = "../../frame/host" }
anonify-io-types = { path = "../anonify-io-types" }
sgx_types = "1.1.1"
thiserror = "1.0"
anyhow = "1.0"
ed25519-dalek = "1"
parking_lot = "0.10"
codec = { package = "parity-scale-codec", version = "1.1" }
web3 = { git = "https://github.com/tomusdrw/rust-web3", rev = "d7393708e257f7ef4ad354917889a8001cf2927c" }
ethabi = "12.0.0"
hex = "0.4"
log = "0.4"
async-trait = "0.1"
