[package]
name = "key-vault-server"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
key-vault-node-server = { path = "../../../nodes/key-vault", default-features = false }
anonify-eth-driver = { path = "../../../modules/anonify-eth-driver", default-features = false }
frame-host = { path = "../../../frame/host" }
actix-web = "3"
failure = "0.1"
tracing-subscriber = "0.2"

[features]
default = ["backup-enable"]
backup-enable = [
    "anonify-eth-driver/backup-enable",
]
