[package]
name = "key-vault-example-server"
version = "0.1.0"
authors = ["cipepser <respepic@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-rt = "1.1"
anyhow = "1.0"
serde_json = "1.0"
thiserror = "1.0"
rustls = "0.19.0"
frame-mra-tls = { path = "../../../frame/mra-tls"}
