[package]
name = "key-vault-example-server"
version = "0.1.0"
authors = ["cipepser <respepic@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-rt = "1.1"
anyhow = "1.0"
serde_json = "1.0"
thiserror = "1.0"
rustls = "0.19.0"
sgx_types = "1.1.1"
env_logger = "0.7"
frame-mra-tls = { path = "../../../frame/mra-tls"}
frame-host = { path = "../../../frame/host" }
key-vault-enclave = { path = "../../../modules/key-vault-enclave" }
key-vault-host = { path = "../../../modules/key-vault-host" }
key-vault-example-api = { path = "../api" }