[package]
name = "key-vault-node-enclave"
version = "0.5.2"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[lib]
name = "anonifyenclave"
crate-type = ["staticlib"]

[dependencies]
frame-config = { path = "../../../frame/config", default-features = false, features = ["sgx"] }
frame-enclave = { path = "../../../frame/enclave" }
frame-types = { path = "../../../frame/types" }
key-vault-enclave = { path = "../../../modules/key-vault-enclave" }
key-vault-ecall-types = { path = "../../../modules/key-vault-ecall-types", default-features = false, features = ["sgx"] }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git"}
anyhow = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
once_cell = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/once_cell-sgx" }
bincode = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/bincode-sgx" }

[features]
default = []
runtime_enabled = []