[package]
name = "frame-enclave"
version = "0.5.3"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
frame-types = { path = "../types" }
frame-common = { path = "../common", default-features = false, features = ["sgx"] }
frame-runtime = { path = "../runtime", default-features = false, features = ["sgx"] }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net","backtrace", "untrusted_fs"] }
anyhow = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git", features = ["derive"] }
thiserror = { git = "https://github.com/mesalock-linux/thiserror-sgx.git" }
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }