[package]
name = "key-vault-node-server"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-rt = "1.1"
anyhow = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
rustls = "0.19.0"
sgx_types = "1.1.1"
tracing = "0.1"
tracing-subscriber = "0.2"
frame-host = { path = "../../frame/host" }
key-vault-host = { path = "../../modules/key-vault-host" }
once_cell = "1.5.2"

[dev-dependencies]
frame-config = { path = "../../frame/config" }
frame-common = { path = "../../frame/common" }
frame-sodium = { path = "../../frame/sodium" }
anonify-eth-driver = { path = "../../modules/anonify-eth-driver" }
state-runtime-node-server = { path = "../../nodes/state-runtime/server" }
state-runtime-node-api = { path = "../../nodes/state-runtime/api" }
web3 = "0.14"
sgx_urts = "1.1.1"
rand_core = "0.5"
rand = "0.7"