[package]
name = "key-vault-node-server"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
actix-web = "3"
anyhow = "1.0"
sgx_types = "1.1.1"
tracing = "0.1"
tracing-subscriber = "0.2"
key-vault-host = { path = "../../modules/key-vault-host" }

[dev-dependencies]
frame-host = { path = "../../frame/host" }
frame-config = { path = "../../frame/config" }
state-runtime-node-server = { path = "../../nodes/state-runtime/server" }
state-runtime-node-api = { path = "../../nodes/state-runtime/api" }
actix-rt = "1.1"
sgx_urts = "1.1.1"
