[package]
name = "encrypted-sql-ops-pg-extension"
version = "0.1.0"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg13"]
pg13 = ["pgx/pg13", "pgx-tests/pg13" ]
pg_test = []

[dependencies]
module-encrypted-sql-ops-ecall-types = { path = "../../../modules/encrypted-sql-ops-ecall-types", default-features = false }
pgx = "0.1.21"
pgx-macros = "0.1.21"
serde = {version = "1.0", features = ["derive"]}

[dev-dependencies]
pgx-tests = "0.1.21"
