[package]
name = "frame-runtime"
version = "0.1.0"
authors = ["osuketh <dish230@gmail.com>"]
edition = "2018"

[dependencies]
frame-common = { path = "../common", default-features = false }
remote-attestation = { path = "../remote-attestation", optional = true }
frame-types = { path = "../types" }
frame-treekem = { path = "../treekem", default-features = false, optional = true }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
anyhow-std = { version = "1.0", package = "anyhow", optional = true }
anyhow-sgx = { rev = "sgx_1.1.3", package = "anyhow", git = "https://github.com/mesalock-linux/anyhow-sgx.git", optional = true }
codec = { package = "parity-scale-codec", version = "1.1", default-features = false, features = ["derive"] }
libsecp256k1 = { version = "0.2", default-features = false }
serde-std = { package = "serde", version = "1", default-features = false, optional = true }
serde-sgx = { package = "serde", git = "https://github.com/mesalock-linux/serde-sgx.git", rev = "sgx_1.1.3", default-features = false, optional = true }
serde_json = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/serde-json-sgx", optional = true }

[features]
default = ["std"]
std = [
    "frame-common/std",
    "anyhow-std",
    "serde-std/std",
    "serde-std/derive",
]
sgx = [
    "frame-common/sgx",
    "sgx_tstd",
    "anyhow-sgx",
    "frame-treekem/sgx",
    "serde-sgx",
    "serde-sgx/derive",
    "remote-attestation",
    "serde_json",
]
