version: '3'
 
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10012:10000"
      - "10013:10002"
    command: ["azurite", "-L", "-l", "/data", "--blobHost", "0.0.0.0", "--tableHost", "0.0.0.0", "-d", "/data/debug.log", "--skipApiVersionCheck"]
    volumes:
      - ./testdata:/data
